"""Update User model for authentication

Revision ID: ed9f5a156879
Revises: c91461490574
Create Date: 2026-10-08 14:06:52.301260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9f5a156879'
down_revision: Union[str, Sequence[str], None] = 'c91461490574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('bench_costs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='Row creation timestamp (UTC)'))
    op.add_column('bench_costs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='Row last-updated timestamp (UTC)'))
    op.drop_constraint('bench_costs_employee_id_fkey', 'bench_costs', type_='foreignkey')
    op.create_foreign_key('bench_costs_employee_id_fkey_cascade', 'bench_costs', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('bench_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='Row creation timestamp (UTC)'))
    op.add_column('bench_history', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()'), comment='Row last-updated timestamp (UTC)'))
    op.drop_constraint('bench_history_employee_id_fkey', 'bench_history', type_='foreignkey')
    op.create_foreign_key('bench_history_employee_id_fkey_cascade', 'bench_history', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    
    op.drop_constraint('employee_costs_employee_id_fkey', 'employee_costs', type_='foreignkey')
    op.create_foreign_key('employee_costs_employee_id_fkey_cascade', 'employee_costs', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False, server_default=sa.text('md5(random()::text)')))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('users', sa.Column('employee_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('cv_uri', sa.String(length=512), nullable=True))
    op.alter_column('users', 'email', existing_type=sa.VARCHAR(length=255), nullable=True)
    
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_foreign_key('fk_users_employee_id', 'users', 'employees', ['employee_id'], ['id'], ondelete='SET NULL')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'cv_uri')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employee_costs', type_='foreignkey')
    op.create_foreign_key(op.f('employee_costs_employee_id_fkey'), 'employee_costs', 'employees', ['employee_id'], ['id'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'bench_history', type_='foreignkey')
    op.create_foreign_key(op.f('bench_history_employee_id_fkey'), 'bench_history', 'employees', ['employee_id'], ['id'])
    op.drop_column('bench_history', 'updated_at')
    op.drop_column('bench_history', 'created_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'bench_costs', type_='foreignkey')
    op.create_foreign_key(op.f('bench_costs_employee_id_fkey'), 'bench_costs', 'employees', ['employee_id'], ['id'])
    op.drop_column('bench_costs', 'updated_at')
    op.drop_column('bench_costs', 'created_at')
    # ### end Alembic commands ###
